config/routes.rb
Rails.application.routes.draw do
  get 'meal_categories/new'
  get 'meal_categories/create'
  devise_for :users
  root to: "pages#home"
  resources :orders, only: [ :new, :create ] do
    member do
      post 'change_status'
    end
  end
  get "/my_meals", to: "meals#view_my_meals", as: "my_meals"
  get "/my_meal/:id", to: "meals#view_my_meal", as: "my_meal"
  get "/my_orders", to: "orders#view_my_orders", as: "my_orders"


  resources :meals do
    collection do
      get 'top_five'
    end
    resources :meal_categories, only: [:new, :create]
    resources :meal_ingredients, only: [:new, :create]
    resources :reviews, only: [ :new, :create ]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path do %>
    <img class="logo" src="<%= image_path('PO-POTES.png') %>"/>
  <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <%= link_to "Add a meal", new_meal_path, class: "nav-link d-block d-sm-none" %>
      </li>
      <li class="nav-item active">
        <%= link_to "My meals", my_meals_path, class: "nav-link d-block d-sm-none" %>
      </li>
      <li class="nav-item active">
        <%= link_to "My orders", my_orders_path, class: "nav-link d-block d-sm-none" %>
      </li>
      <li class="nav-item active">
        <%= link_to "My profile", "#", class: "nav-link d-block d-sm-none" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Log out", destroy_user_session_path, class: "nav-link d-block d-sm-none" %>
      </li>

      <button class="border-none add-meal" type="button" >
          <%= link_to "Add a meal", new_meal_path %>
        </button>

      <li class="dropdown align-self-center d-none d-sm-block mr-3">
        <button class="dropdown-toggle border-none" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My kitchen
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% if user_signed_in? %>

          <%= link_to "My meals", my_meals_path, class: "dropdown-item" %>
          <%= link_to "My orders", my_orders_path, class: "dropdown-item" %>
          <%= link_to "My profile", "#", class: "dropdown-item d-block d-sm-none" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <% end %>
        </div>
      </li>


      <li class="nav-item dropdown">
          <%= image_tag "https://resize-parismatch.lanmedia.fr/img/var/news/storage/images/paris-match/people-a-z/javier-bardem/6033180-8-fre-FR/Javier-Bardem.jpg", class: "avatar dropdown-toggle d-none d-sm-block", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

      </li>
    </ul>
  </div>
</div>

app/views/shared/_search-bar.html.erb
<%= form_tag meals_path, method: :get, class: "searchbar form-inline" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "td form-control mr-3 w-75",
    placeholder: "Search by meal name, food category, ingredient or cook username"
  %>

<% end %>