config/routes.rb
Rails.application.routes.draw do
  get 'meal_categories/new'
  get 'meal_categories/create'
  devise_for :users
  root to: "pages#home"
  resources :orders, only: [ :new, :create ] do
    member do
      post 'change_status'
    end
  end
  get "/my_meals", to: "meals#view_my_meals", as: "my_meals"
  get "/my_meal/:id", to: "meals#view_my_meal", as: "my_meal"
  get "/my_orders", to: "orders#view_my_orders", as: "my_orders"


  resources :meals do
    collection do
      get 'top_five'
    end
    resources :meal_categories, only: [:new, :create]
    resources :meal_ingredients, only: [:new, :create]
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :meal

  validates :order_quantity, presence: true, numericality: { only_integer: true }
  validates :pick_up_date, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @order = Order.all
  end

  def view_my_orders
    @my_orders = Order.where(user: current_user)
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @meal = Meal.find(params[:meal_id])
    if @order.order_quantity.to_i <= @meal.left_quantity
      @order.meal = @meal
      if @order.save
        flash[:notice] = "Your order has been successfully created!"
        redirect_to my_orders_path
      else
        render 'meals/show'
      end
    else
      flash[:notice] = "Too late! There is only #{@meal.left_quantity}"
      redirect_to meal_path(@meal)
    end
  end

  def change_status
    @order = Order.find(params[:id])
    params[:status] == "accept" ? @order.status = 'accepted' : @order.status = 'declined'
    @order.save
    redirect_to my_meals_path
  end

  private

  def order_params
    params.require(:order).permit(:order_quantity, :pick_up_date)
  end
end

app/views/orders/view_my_orders.html.erb
<div class="container-orders-detail">
  <h1>My orders</h1>
    <% @my_orders.each do |order| %>
      <div class="my-orders-red">

        <div class="my-orders-pic-crop">
          <%= cl_image_tag order.meal.photo, crop: :fill %>
        </div>

        <div class="my-orders-info-details">

          <div class="my-orders-info-details-text">
            <h2><%= order.meal.name %></h2>
            <h5>🗓 Ordered on the <strong><%= order.pick_up_date %></strong></h5>
            <h5>Cooked with ❤️ by <strong><%= order.meal.user.username %></strong></h5>
            <h5>To be shared with <strong><%= order.order_quantity %></strong> friends 👨‍👩‍👧 </h5>

            <div class="order-price-and-status">

              <div class="order-price-details">
                <h2><%= order.order_quantity * order.meal.unit_price%> euros</h2>
              </div>

              <span class="my-order-status"> <%= order.status %></span>
              </div>

            </div>
          </div>

          <div class="my-orders-review-display">
            <%= link_to new_meal_review_path(order.meal), class: "button" do %>
            <i class="fas fa-user-edit"></i>
            Add a review
          <% end %>
          </div>
        </div>
      <% end %>
    </div>