config/routes.rb
Rails.application.routes.draw do
  get 'meal_categories/new'
  get 'meal_categories/create'
  devise_for :users
  root to: "pages#home"
  resources :orders, only: [ :new, :create ] do
    member do
      post 'change_status'
    end
  end
  get "/my_meals", to: "meals#view_my_meals", as: "my_meals"
  get "/my_meal/:id", to: "meals#view_my_meal", as: "my_meal"
  get "/my_orders", to: "orders#view_my_orders", as: "my_orders"


  resources :meals do
    collection do
      get 'top_five'
    end
    resources :meal_categories, only: [:new, :create]
    resources :meal_ingredients, only: [:new, :create]
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many :meal_ingredients, dependent: :destroy
  has_many :ingredients, through: :meal_ingredients
  has_many :eater_users, through: :orders, source: :user
  has_many :reviews
  has_many :meal_categories, dependent: :destroy
  has_many :categories, through: :meal_categories



  # CATEGORIES = ["Chinese", "French", "Sushi", "Dessert", "Grandma", "Italian", "Healthy", "Moroccan", "Burger", "Vegan", "Thaï", "Hawaïan"]

  pg_search_scope :global_search,
    against: [ :name, :description, :category ],
    associated_against: {
      user: [ :username]
    },
    using: {
      tsearch: { prefix: true }
    }


  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  # validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :unit_price, presence: true, numericality: { only_integer: true }
  validates :quantity_max, presence: true, numericality: { only_integer: true }
  # validates :start_availability_date, presence: true
  # validates :end_availability_date, presence: true
  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  def can_delete?
    !self.orders.pluck(:status).include?('accepted')
  end

  def left_quantity
    if !can_delete?
      self.quantity_max - self.orders.where(status: "accepted").pluck(:order_quantity).reduce(:+)
    else
      self.quantity_max
    end
  end

  def rating_average
    self.reviews.map { |review| review.rating }.reduce(:+) / self.reviews.count.to_f
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_meal, only: [:show, :edit, :update, :destroy]


  def index
    @query = params[:query]
    @query_on_category = params[:category]

    if @query.present?
      @meals = Meal.geocoded.global_search(params[:query])
    elsif @query_on_category.present?
      categories = @query_on_category.select { |k, v| v == '1' }.keys
      @meals = Meal.geocoded.select { |m| categories.include?(m.category) }
    else
      @meals = Meal.geocoded
  end

    @markers = @meals.map do |meal|
      {
        lat: meal.latitude,
        lng: meal.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { meal: meal }),
        image_url: helpers.asset_url('carottes.png')
      }
    end
  end

  def show
    @meal = Meal.find(params[:id])
    @order = Order.new
  end

  def view_my_meals
    @my_meals = Meal.where(user: current_user)

    my_received_orders = []
    @my_meals.each do |meal|
      my_received_orders << meal.orders
    end

    @my_received_orders = my_received_orders.flatten
  end



  def view_my_meal
    @my_meals = Meal.where(user: current_user)
    @my_meal = @my_meals.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    if @meal.save
      redirect_to meal_path(@meal)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @meal.update(meal_params)
    redirect_to meal_path(@meal)
  end

  def destroy
    @meal.destroy
    redirect_to my_meals_path
  end

  private

  def set_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:name, :description, :address, :category, :unit_price, :quantity_max, :start_availability_date, :end_availability_date, :photo)
  end
end

app/views/meals/_form.html.erb
<%= simple_form_for(@meal) do |f| %>
  <%= f.input :name, label: 'Nom du plat' %>
  <%= f.input :description, label: 'Description'  %>
  <%= f.input :address, label: 'Votre adresse' %>
  <%#= f.input :category, label: 'Choisissez une catégorie', collection: Meal::CATEGORIES %>
  <%= f.input :unit_price, label: "Prix d'une part" %>
  <%= f.input :quantity_max, label: 'Nombre de parts maximum' %>
  <%= f.input :start_availability_date, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :end_availability_date, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

  <%= f.submit "Add a meal", class: "button"  %>
  <% end %>

app/views/meals/_info_window.html.erb
<h2><%= meal.name %></h2>
<div class="meal-pic">
  <span> <%= cl_image_tag meal.photo %> </span>
</div>
<p><%= meal.address %></p>
<button class="button map-link">
  <%= link_to "Buy", meal_path(meal) %>
</button>

app/views/meals/edit.html.erb
<div class="form-meals">
  <h2> Edit your meal </h2>
  <%= render 'form', meal: @meal %>
  <p> <%= link_to 'ajouter allergène', new_meal_meal_ingredient_path(@meal) %> </p>

<ul><% @meal.ingredients.each do |ingredient| %>
      <li><%= ingredient.name %> </li>
  <% end %></ul>
</div>

app/views/meals/index.html.erb
<div class="container mt-3 ">


<!-- adding searchbar-->

<%= render '/shared/search-bar' %>


<!--   <h2>Category is...</h2> -->
<h5>Search by...</h5>
  <div class="category-container">

      <div class="category-item">


          <div class="card-category dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" style="background-color: #E89972">
          Category
          </div>

          <div class="dropdown-menu">
            <% Category.pluck(:name).each do |category| %>
              <li>
                <%= link_to category, meals_path(:query => category), class: "dropdown-item", as: :boolean %>
              </li>
            <% end %>
          </div>
      </div>

      <div class="category-item">
          <div class="card-category dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" style="background-color: #F8E865" #A4D1C8>
            Ingredients
          </div>

          <div class="dropdown-menu">
            <% Ingredient.pluck(:name).each do |ingredient| %>
              <li>
                <%= link_to ingredient, meals_path(:query => ingredient), class: "dropdown-item" %>
              </li>
            <% end %>
          </div>
      </div>

      <div class="category-item">
        <div class="card-category dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" style="background-color: #A4D1C8">
          Pick-up date
        </div>
        <%#= simple_form_for(@meal) do |f| %>
        <%#= f.input :pick_up_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%# end %>
      </div>
  </div>
</div>
<div class="container mt-3">

<!-- dynamic count according to the search -->
<div class="row">
    <div class="col">
      <% if @query %>
        <h5>You searched for <strong><%= @query %></strong>. <%=pluralize(@meals.count,'meal')%> out of the <%= Meal.count %> available in our big marmite.🍴</h5>
      <% elsif @query_on_category %>
        <h5>You searched for <strong><%= @query_on_category %></strong>. <%=pluralize(@meals.count,'meal')%> out of the <%= Meal.count %> available in our big marmite.🍴</h5>
      <% else %>
        <h5>🍗 All <%= Meal.count %> meals.🍗</h5>
      <% end %>
    </div>
</div>



<!-- mosaic of meals -->
<div class="cards_and_map_container">
  <div class="row cards-row">

    <% @meals.each do |meal| %>
      <div class="box col-6">
        <%= link_to meal_path(meal) do %>
          <div class="meal-card">

            <% if meal.left_quantity == 0 || meal.left_quantity < 0 %>

              <span class="badge badge-pill badge-warning">
                Sold Out
              </span>
            <% end %>
            <div class="meal-card-image" style="background: url('<%= cl_image_path meal.photo %>')"></div>
            <div class="meal-card-content">
              <div class="meal-card-title-and-category">
                <div class="meal-card-title"><h4><%= meal.name %></h4></div>
                <% meal.categories.each do |category| %>
                  <span><%= category.name %></span>
                <% end %>
              </div>
                <div class="meal-card-attributes d-flex align-items-end">
                  <div class="d-flex align-items-center">
                    <span><%= meal.quantity_max %></span>
                    <i class="material-icons ml-1">people</i>

                  </div>
                  <div class="d-flex ml-5">
                    <div class="order-count"><%= meal.left_quantity %></div>
                    <span><p class="ml-1">left</p></span>
                  </div>

                  <div class="d-flex ml-5 align-items-center">
                    <%= meal.unit_price %>
                    <i class="material-icons ml-1">euro_symbol</i>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <div id="map" style="width: 40%; height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/meals/new.html.erb
<div class="form-meals">
  <h2> Entrer votre délicieux repas </h2>
  <%= render 'form', meal: @meal %>
</div>

<div class="back-button-container d-flex">
  <%= link_to "Back to meals", meals_path, class: "little-button-yellow" %>
</div>

app/views/meals/show.html.erb
<div class="meal-banner" style="background-image: url('<%= cl_image_path @meal.photo %>')">
</div>

<div class="container">
  <div class="meal-main-container">
    <div class="left-content">
      <!-- div titre + photo -->
      <div class="d-flex justify-content-between">
        <div>
          <h1><%= @meal.name.capitalize %></h1>
        </div>
        <div>
        <!-- div photo + nom -->
          <% if @meal.user.photo? %>
            <%= cl_image_tag @meal.user.photo, class:"user_pic_and_name", gravity: :face, crop: :thumb %>
          <% else %>
            <img src="https://www.getdigital.fr/web/getdigital/gfx/products/__generated__resized/380x380/Aufkleber_Trollface.jpg" alt="" class="user_pic_and_name">
          <% end %>
          <p><%= @meal.user.username %></p>
        </div>
      </div>
      <p class="meal_category_badge"><%= @meal.category %></p>
      <% @meal.ingredients.each do |ingredient| %>
        <p class="allergies"><%= ingredient.name %> </p>
      <% end %>
      <div class="meal-info-details">
        <p><%= @meal.description %> </p>
        <p> Nombre de parts max : <%= @meal.quantity_max %> </p>
        <p> Nombre de parts dispo : <%= @meal.left_quantity %> </p>
      </div>
      <hr>
      <span class="d-flex">
        <% if @meal.reviews.present? %>
            <h3 class="pb-2 mr-3">Reviews</h3>
            <% @meal.rating_average.floor.times do %>
              <i class="fas fa-star"></i>
            <% end %>
            <% if @meal.rating_average % 1 != 0 %>
              <i class="fas fa-star-half"></i>
          <% end %>
        <% end %>
      </span>
      <div class="">
        <% @meal.reviews.each do |review| %>
          <span class="d-flex justify-content-between">
            <p class="review-author"><%= review.user.username %></p>
            <span><% review.rating.times do %>
              <i class="fas fa-star"></i>
              <% end %>
              <% (5 - review.rating).times do %>
                <i class="far fa-star"></i>
            <% end %></span>
          </span>
          <span><p><%= review.content %></p></span>
        <% end %>
      </div>
    </div>
    <!-- div photo + nom -->
    <div class="right-content">

      <% if @meal.user != current_user %>
        <div class="checkout card p-3">
            <div class="d-flex py-3 border-bottom">
              <span class="price-per-serving"><%= @meal.unit_price %></span>
             € /serving
              <span class="total-price" data-meal="<%= @meal.to_json %>"></span>€
            </div>
            <%= simple_form_for(@order) do |f| %>
              <%= hidden_field_tag :meal_id, @meal.id %>
              <%= f.input :pick_up_date %>
              <%= f.input :order_quantity %>
              <%= f.button :submit, class: "button" %>
            <% end %>
          <% else %>
          <%= link_to 'Ajouter allergène', new_meal_meal_ingredient_path(@meal),  class: "button" %>
        </div>
      <% end %>

    </div>
  </div>
  <!-- div left content -->
</div>

app/views/meals/view_my_meal.html.erb
<div class="container py-2">
  <div class="row">
    <div class="col-8">
      <div class="meal_header d-flex justify-content-between py-3 border-bottom">
        <div class="meal_big_titles">
          <h1><%= @meal.name.capitalize %></h1>
          <h3 class=""><%= @meal.category %></h3>
        </div>
        <div class="user_pic_and_name d-flex flex-column align-items-center">
          <img src="https://resize-parismatch.lanmedia.fr/img/var/news/storage/images/paris-match/people-a-z/javier-bardem/6033180-8-fre-FR/Javier-Bardem.jpg" alt="" class="">
          <p><%= @meal.user.username %></p>
        </div>
      </div>

      <div class="meal_text">
        <p><%= @meal.description %></p>
      </div>
    </div>


  <!--   <div class="location">

    </div> -->
  </div>
</div>

app/views/meals/view_my_meals.html.erb
<div class="container">
  <h2 class="mt-3">To be cooked</h2>
  <% @my_received_orders.each do |order| %>
    <% if order.status == "accepted" %>
        <div class="card-items">
          <%= cl_image_tag order.meal.photo %>
        <div class="card-item-infos">
          <p><%= order.meal.name %></p>
          <p><%= order.user.username %></p>
          <p>Status <%= order.status %></p>
        </div>
      </div>
    <% end %>
  <% end %>

    <h2 class="mt-3">My received orders </h2>
    <% @my_received_orders.each do |order| %>
    <% if order.status != "accepted" %>
      <div class="card-items">
        <%= cl_image_tag order.meal.photo %>
        <div class="card-item-infos">
          <p><%= order.meal.name %></p>
          <p><%= order.user.username %></p>
          <p>Status <%= order.status %></p>
          <p><%= link_to "Accept", change_status_order_path(order, :status => "accept"), method: :POST, class:"btn btn-outline-dark" %></p>
          <p><%= link_to "Decline", change_status_order_path(order, :status => "decline"), method: :POST, class:"btn btn-outline-dark" %> </p>
        </div>
      </div>
    <% end %>
  <% end %>


  <h2 class="mt-3">My meals</h2>
      <% @my_meals.each do |meal| %>
        <div class="card-items" >
          <%= cl_image_tag meal.photo %>
          <div class="card-item-infos">
            <p><%= meal.name %></p>
            <% meal.categories.each do |category| %>
              <span><%= category.name %></span>
            <% end %>
            <p><%=  meal.quantity_max %></p>

            <% if meal.can_delete? %>

              <p><%= link_to "Edit", edit_meal_path(meal.id), class:"btn btn-outline-dark" %></p>
              <p><%= link_to "Delete", meal_path(meal.id), class:"btn btn-outline-dark",
                method: :delete,
                data: { confirm: "Are you sure?" } %>
             </p>

            <% end %>
          </div>
        </div>
    <% end %>

</div>